02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Models/Comment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Blog.Models
{
    public class Comment
    {
        public Comment() { }

        public Comment(string content, string authorId, int articleId)
        {
            this.Content = content;
            this.AuthorId = authorId;
            this.ArticleId = articleId;
            this.DateAdded = DateTime.Now;
        }

        [Key]
        public int Id { get; set; }

        [Required]
        public string Content { get; set; }

        [ForeignKey("Article")]
        public int ArticleId { get; set; }

        public Article Article { get; set; }

        [ForeignKey("Author")]
        public string AuthorId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public DateTime DateAdded { get; set; }

        public bool IsAuthor(string name)
        {
            return this.Author.UserName == name;
        }
    }
}

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Models/CommentViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Blog.Models
{
    public class CommentViewModel
    {
        public CommentViewModel() { }

        public CommentViewModel(int id, string content, string authorId)
        {
            this.Id = id;
            this.AuthorId = authorId;
            this.Content = content;
            this.DateAdded = DateTime.Now;

        }

        public int Id { get; set; }

        [Required]
        public string Content { get; set; }

        public string AuthorId { get; set; }

        public int ArticleId { get; set; }

        public virtual ApplicationUser Author { get; set; }

        public DateTime DateAdded { get; set; }
    }
}

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Controllers/ArticleController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data;
using Blog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.Controllers
{
    public class ArticleController : Controller
    {
        public ApplicationDbContext context { get; set; }

        public UserManager<ApplicationUser> UserManager { get; set; }

        public ArticleController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.UserManager = userManager;
            this.context = context;
        }

        private bool UserIsAuthorizedToEdit(Article article)
        {
            var isAdmin = this.User.IsInRole("Admin");
            var isAuthor = article.IsAuthor(this.User.Identity.Name);

            return isAdmin || isAuthor;
        }

        private ApplicationUser GetCurrentUser()
        {
            return this
                    .context
                    .Users
                    .Where(u => u.UserName == this.User.Identity.Name)
                    .First();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction(nameof(List));
        }

        [HttpGet]
        public IActionResult List()
        {
            var articles = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .ToList();

            return View(articles);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();

            var article = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .Include(a => a.Comments)
                                .ThenInclude(c => c.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (article == null) return NotFound();

            return View(article);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(ArticleViewModel articleModel)
        {
            if (ModelState.IsValid == false)
            {
                return View(articleModel);
            }

            var userId = this.GetCurrentUser().Id;
            var article = new Article(articleModel.Title, articleModel.Content, userId);

            this.context.Add(article);
            this.context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();

            var article = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (article == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(article) == false) return Forbid();

            var articleModel = new ArticleViewModel(article.Id, article.Title, article.Content, article.AuthorId);
            return View(articleModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(ArticleViewModel articleModel)
        {
            if (ModelState.IsValid == false)
            {
                return View(articleModel);
            }

            var article = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == articleModel.Id);

            if (article == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(article) == false) return Forbid();

            article.Title = articleModel.Title;
            article.Content = articleModel.Content;

            this.context.Update(article);
            this.context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound();

            var article = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (article == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(article) == false) return Forbid();

            var articleModel = new ArticleViewModel(article.Id, article.Title, article.Content, article.AuthorId);
            return View(articleModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(ArticleViewModel articleModel)
        {
            var article = this
                            .context
                            .Articles
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == articleModel.Id);

            if (article == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(article) == false) return Forbid();

            this.context.Remove(article);
            this.context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Controllers/CommentController.cs
using System;
using System.Linq;
using Blog.Data;
using Blog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Blog.Controllers
{
    public class CommentController : Controller
    {
        public ApplicationDbContext context { get; set; }

        public UserManager<ApplicationUser> UserManager { get; set; }

        public CommentController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            this.UserManager = userManager;
            this.context = context;
        }

        private bool UserIsAuthorizedToEdit(Comment comment)
        {
            var isAdmin = this.User.IsInRole("Admin");
            var isAuthor = comment.IsAuthor(this.User.Identity.Name);

            return isAdmin || isAuthor;
        }

        private ApplicationUser GetCurrentUser()
        {
            return this
                    .context
                    .Users
                    .First(u => u.UserName == this.User.Identity.Name);
        }

        [HttpGet]
        public IActionResult Index()
        {
            return RedirectToAction(nameof(Details));
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null) return NotFound();

            var comment = this
                            .context
                            .Comments
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (comment == null) return NotFound();

            return View(comment);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create(int? articleId)
        {
            if (articleId == null) return NotFound();

            return View(new CommentViewModel { ArticleId = articleId.Value });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Create(CommentViewModel commentModel)
        {
            if (ModelState.IsValid == false) return View(commentModel);

            var userId = this.GetCurrentUser().Id;

            var comment = new Comment(commentModel.Content, userId, commentModel.ArticleId);

            this.context.Comments.Add(comment);
            this.context.SaveChanges();

            // return RedirectToAction(nameof(Details), new { comment.Id });
            return RedirectToAction(nameof(Details), nameof(Article), new { id = comment.ArticleId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit(int? id)
        {
            if (id == null) return NotFound();

            var comment = this
                            .context
                            .Comments
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (comment == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(comment) == false) return Forbid();

            var commentModel = new CommentViewModel(comment.Id, comment.Content, comment.AuthorId);
            return View(commentModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(CommentViewModel commentModel)
        {
            if (ModelState.IsValid == false) return View(commentModel);

            var comment = this
                            .context
                            .Comments
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == commentModel.Id);

            if (comment == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(comment) == false) return Forbid();

            comment.Content = commentModel.Content;

            this.context.Comments.Update(comment);
            this.context.SaveChanges();

            // return RedirectToAction(nameof(Details), new { comment.Id });
            return RedirectToAction(nameof(Details), nameof(Article), new { id = comment.ArticleId });
        }

        [HttpGet]
        [Authorize]
        public IActionResult Delete(int? id)
        {
            if (id == null) return NotFound();

            var comment = this
                            .context
                            .Comments
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == id);

            if (comment == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(comment) == false) return Forbid();

            var commentModel = new CommentViewModel(comment.Id, comment.Content, comment.AuthorId);
            return View(commentModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Delete(CommentViewModel commentModel)
        {
            var comment = this
                            .context
                            .Comments
                            .Include(a => a.Author)
                            .FirstOrDefault(a => a.Id == commentModel.Id);

            if (comment == null) return NotFound();
            if (this.UserIsAuthorizedToEdit(comment) == false) return Forbid();

            this.context.Comments.Remove(comment);
            this.context.SaveChanges();

            // return RedirectToAction("Index", "Home");
            return RedirectToAction(nameof(Details), nameof(Article), new { id = comment.ArticleId });
        }
    }
}

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Views/Comment/Create.cshtml
@model Blog.Models.CommentViewModel
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="well">
        <h2>Create Comment</h2>
        <form asp-action="Create" class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Content" class="control-label col-sm-4"></label>
                <textarea asp-for="Content" class="form-control" rows="7"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <input hidden asp-for="ArticleId"></input>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    <a asp-controller="Article" asp-action="Details" asp-route-id="@Model.ArticleId" class="btn btn-default">Cancel</a>
                    <input type="submit" value="Create" class="btn btn-success" />
                </div>
            </div>
        </form>
    </div>
</div>

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Views/Comment/Delete.cshtml
@model Blog.Models.CommentViewModel

@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="well">
        <h2>Delete Comment</h2>
        <form asp-action="Delete" class="form-horizontal">
            <div class="form-group">
                <label asp-for="Content" class="control-label col-sm-4"></label>
                <textarea asp-for="Content" class="form-control" rows="7" readonly></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    <input type="hidden" asp-for="Id" />
                    <a asp-controller="Comment" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-default">Cancel</a>
                    <input type="submit" value="Delete" class="btn btn-danger" />
                </div>
            </div>
        </form>
    </div>
</div>

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Views/Comment/Details.cshtml
@model Blog.Models.Comment

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <article>
        <p>
            @Html.DisplayFor(model => model.Content)
        </p>
        <small class="author">
            -- author @Html.DisplayFor(model => model.Author.FullName)
        </small>
        <footer class="pull-right">
            @if (User.IsInRole("Admin") || Model.IsAuthor(User.Identity.Name))
            {
                <a class="btn btn-success btn-xs" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                <a class="btn btn-danger btn-xs" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            }
            <a asp-controller="Article" asp-action="Details" asp-route-id="@Model.ArticleId" class="btn btn-default btn-xs">Back</a>
            <!-- <a class="btn btn-default btn-xs" asp-action="Index">Back</a> -->
        </footer>
    </article>
</div>

02-tech/03-software-technologies/07-ccsharp/02-blog/Blog/Blog/Views/Comment/Edit.cshtml
@model Blog.Models.CommentViewModel

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <div class="well">
        <h2>Edit Article</h2>
        @using (Html.BeginForm("Edit", "Comment", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()

            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.AuthorId)

            <div class="form-group">
                @Html.LabelFor(m => m.Content, new { @class = "control-label col-sm-4" })
                <div class="col-sm-4">
                    @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "7" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-4 col-sm-offset-4">
                    <!-- @Html.ActionLink("Cancel", "Details", "Comment", @Model.Id, new { @class = "btn btn-default" }) -->
                    <a asp-controller="Comment" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-default">Back</a>
                    <input type="submit" value="Edit" class="btn btn-success" />
                </div>
            </div>
        }
    </div>
</div>