06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Areas/Administration/Controllers/AdministrationController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    using MyRecipes.Common;
    using MyRecipes.Web.Controllers;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
    [Area("Administration")]
    public class AdministrationController : BaseController
    {
    }
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Areas/Administration/Controllers/DashboardController.cs
namespace MyRecipes.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class DashboardController : AdministrationController
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Controllers/BaseController.cs
namespace MyRecipes.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;

    public class BaseController : Controller
    {
    }
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Controllers/HomeController.cs
namespace MyRecipes.Web.Controllers
{
    using System.Diagnostics;

    using Microsoft.AspNetCore.Mvc;

    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Home;

    public class HomeController : BaseController
    {
        private readonly IGetCountsService countsService;

        public HomeController(IGetCountsService countsService)
        {
            this.countsService = countsService;
        }

        public IActionResult Index()
        {
            var counts = this.countsService.GetCounts();
            var viewModel = new IndexViewModel
            {
                CategoriesCount = counts.CategoriesCount,
                ImagesCount = counts.ImagesCount,
                IngredientsCount = counts.IngredientsCount,
                RecipesCount = counts.RecipesCount,
            };

            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Controllers/RecipesController.cs
namespace MyRecipes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    using MyRecipes.Data.Models;
    using MyRecipes.Services.Data;
    using MyRecipes.Web.ViewModels;
    using MyRecipes.Web.ViewModels.Recipes;

    public class RecipesController : BaseController
    {
        private readonly ICategoriesService categoriesService;
        private readonly IRecipesService recipesService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public RecipesController(
            ICategoriesService categoriesService,
            IRecipesService recipesService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment webHostEnvironment)
        {
            this.categoriesService = categoriesService;
            this.recipesService = recipesService;
            this.userManager = userManager;
            this.environment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult All(int id = 1)
        {
            var firstPage = 1;
            var pageNumberIsValid = firstPage <= id && id <= this.recipesService.GetCount();
            if (pageNumberIsValid == false)
            {
                return this.NotFound();
            }

            const int itemsPerPage = 12;
            var viewModel = new PagingViewModel
            {
                ItemsPerPage = itemsPerPage,
                PageNumber = id,
                RecipesCount = this.recipesService.GetCount(),
                Recipes = this.recipesService.GetAll<RecipeInListViewModel>(id, itemsPerPage),
            };

            // return this.View();
            return this.View(viewModel);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreateRecipeInputModel();
            viewModel.CategoriesItems = this.categoriesService.GetAllKeysAsKeyValuePairs();

            return this.View(viewModel);
        }

        [HttpPost]
        // [AllowedExtensions]
        public async Task<IActionResult> Create(CreateRecipeInputModel input)
        {
            if (this.ModelState.IsValid == false)
            {
                input.CategoriesItems = this.categoriesService.GetAllKeysAsKeyValuePairs();
                return this.View(input);
            }

            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.recipesService.CreateAsync(input, user.Id, $"{this.environment.WebRootPath}/images");
            }
            catch (Exception exception)
            {
                this.ModelState.AddModelError(string.Empty, exception.Message);
                input.CategoriesItems = this.categoriesService.GetAllKeysAsKeyValuePairs();

                return this.View(input);
            }

            return this.RedirectToAction(nameof(RecipesController.All), nameof(RecipesController));
        }

        [HttpGet]
        public IActionResult Details()
        {
            return this.View();
        }
    }
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model MyRecipes.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<h1>@this.ViewData["Title"]</h1>
Settings: @this.Model.SettingsCount

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Views/Recipes/Create.cshtml
@model MyRecipes.Web.ViewModels.Recipes.CreateRecipeInputModel
@{
    this.ViewData["Title"] = "Add new recipe";
    var categoryItems = this.Model.CategoriesItems.Select(x => new SelectListItem(x.Key, x.Value));
}

<h1 class="col-md-6 offset-md-3">@this.ViewData["Title"]</h1>

<form method="POST" class="col-md-6 offset-md-3" enctype="multipart/form-data">
    <div asp-validation-summary="All"></div>
    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Instructions"></label>
        <textarea asp-for="Instructions" class="form-control" rows="5"></textarea>
        <span asp-validation-for="Instructions" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PreparationTime"></label>
        <input asp-for="PreparationTime" class="form-control" />
        <span asp-validation-for="PreparationTime"></span>
    </div>
    <div class="form-group">
        <label asp-for="CookingTime"></label>
        <input asp-for="CookingTime" class="form-control" />
        <span asp-validation-for="CookingTime"></span>
    </div>
     <div class="form-group">
        <label asp-for="PortionsCount"></label>
        <input asp-for="PortionsCount" class="form-control" />
        <span asp-validation-for="PortionsCount" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoryId"></label>
        <select asp-for="CategoryId" class="form-control" asp-items="categoryItems"></select>
        <span asp-validation-for="CategoryId"></span>
    </div>
    <div class="form-control" id="IngredientsContainer">
        <label asp-for="Ingredients"></label>
        <a class="btn btn-success" onclick="AddMoreIngredients()">+</a>
    </div>

    <input type="submit" class="btn btn-primary form-control"/>
</form>

@section Scripts {
    <script>
        let ingredientIndex = 1;
        function AddMoreIngredients() {

            let ingredientNumber = `ingredient${ingredientIndex}`;

            let nameLabel = $(`<label for='${ingredientIndex}'>Name</label>`);
            let nameInput = $(`<input class="" type='text' name='Ingredients[${ingredientIndex}].IngredientName' id='${ingredientIndex}input' />`);

            let quantityLabel = $(`<label for='${ingredientIndex}'>Quantity</label>`);
            let quantityInput = $(`<input class="" type='text' name='Ingredients[${ingredientIndex}].Quantity' id='${ingredientIndex}quantity' />`);

            let ingredientsRow=$("<div class='col-md-6 form-control clearfix'></div>");
            ingredientsRow.append(nameLabel, nameInput, quantityLabel, quantityInput);

            $("#IngredientsContainer").append(ingredientsRow);
        }
    </script>
}

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Views/Recipes/all.cshtml
@model MyRecipes.Web.ViewModels.PagingViewModel
@{
    this.ViewData["Title"] = $"All recipes, page {Model.PageNumber}";
}

<h1>@this.ViewData["Title"]</h1>
<hr />

<div class="container">
    <div class="row">
        @foreach (var recipe in this.Model.Recipes)
        {
            <div class="card col-md-3">
                <img class="card-img-top" src="@recipe.ImageUrl" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">
                        @recipe.Name
                    </h5>
                    <p class="card-text">
                        @recipe.CategoryName
                    </p>
                </div>
            </div>
        }
    </div>
</div>
<hr />

<partial name="_PagingPartial" model="@Model" />

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Views/Shared/_Layout.cshtml
@using MyRecipes.Common
<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
    </head>

    <body>
        <div id="wrapper" class="wrapper">
            <header>
                <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                            <partial name="_LoginPartial" />
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="All">All recipes</a>
                                </li>
                                @if (this.User.Identity.IsAuthenticated)
                            {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Create">Create recipe</a>
                                        </li>
                            }
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>

            <div class="container">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-3">
                    @this.RenderBody()
                </main>
            </div>

            <footer class="ranna-bg-dark">
                <div class="container">
                    &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
            </div>

            <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
            <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
            <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
            @await this.RenderSectionAsync("Scripts", required: false)
    </body>

</html>

06-c#-web/02-asp-net-core/01-workshop-recipes/Web/MyRecipes.Web/Views/Shared/_PagingPartial.cshtml
@model PagingViewModel
<nav aria-label="..." class="mx-auto">
    <ul class="pagination justify-content-center">
        @if (Model.HasPreviousPage)
        {
            <li class="page-item">
                <a asp-action="All" asp-route-id="@Model.FirstPage" class="page-link">
                    First
                </a>
            </li>
            <li class="page-item">
                <a asp-action="All" asp-route-id="@Model.PreviousPageNumber" asp- class="page-link">
                    @Model.PreviousPageNumber
                </a>
            </li>
        }
        <li class="page-item active" aria-current="page">
            <span class="page-link">@Model.PageNumber
            </span>
        </li>
        @if (Model.HasNextPage)
        {
            <li class="page-item">
                <a asp-action="All" asp-route-id="@Model.NextPageNumber" class="page-link">
                    @Model.NextPageNumber
                </a>
            </li>
            <li class="page-item">
                <a asp-action="All" asp-route-id="@Model.LastPage" class="page-link">
                    Last
                </a>
            </li>
        }
    </ul>
</nav>